name: Deploy Next.js to GitHub Pages

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Create .env file
        working-directory: ./client
        run: |
          echo NEXT_PUBLIC_API_URL=https://cmmc.jaktool.com >> .env
          echo NEXT_PUBLIC_FRAMEWORK_VERSION=$(sha1sum public/data/sp_800_171_3_0_0/framework.json | awk '{print $1}') >> .env
          echo NEXT_PUBLIC_CSP="default-src 'self'; script-src 'self' 'unsafe-inline'; style-src-attr 'self' 'unsafe-inline'"

      - name: Retrieve the cached "node_modules" directory (if present)
        uses: actions/cache@v3
        id: node-cache
        with:
          path: ./client/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('./client/package-lock.json') }}

      - name: Install dependencies
        run: npm install
        if: steps.node-cache.outputs.cache-hit != 'true'
        working-directory: ./client

      - name: Build App
        run: npm run build
        working-directory: ./client

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: cmmc.jaktool.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/out  # This is the default output directory for `next export`

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
