name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if different

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Create .env file
        working-directory: ./client
        run: |
          echo NEXT_PUBLIC_API_URL=https://nist-sp-800-171.neal.codes >> .env

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Build App
        run: npm run build
        working-directory: ./client

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: nist-sp-800-171.neal.codes
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/out  # This is the default output directory for `next export`